// NOTE: combined example.js with worker.js, because firefox currently doesn't support async module loading in service workers

var createSolver = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(createModule = {})  {

var h;h||(h=typeof createModule !== 'undefined' ? createModule : {});var aa,ba;h.ready=new Promise(function(a,b){aa=a;ba=b});var ca=Object.assign({},h),da="./this.program",ea=(a,b)=>{throw b;},k="",fa;k=self.location.href;_scriptDir&&(k=_scriptDir);0!==k.indexOf("blob:")?k=k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1):k="";fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};
var ha=h.print||console.log.bind(console),l=h.printErr||console.warn.bind(console);Object.assign(h,ca);ca=null;h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);var p;h.wasmBinary&&(p=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!=typeof WebAssembly&&q("no native wasm support detected");var ia,ja=!1,ka,la="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function w(a,b){for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&la)return la.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var m=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|m:(e&7)<<18|g<<12|m<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c}
function ma(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var m=a.charCodeAt(g);if(55296<=m&&57343>=m){var t=a.charCodeAt(++g);m=65536+((m&1023)<<10)|t&1023}if(127>=m){if(c>=d)break;b[c++]=m}else{if(2047>=m){if(c+1>=d)break;b[c++]=192|m>>6}else{if(65535>=m){if(c+2>=d)break;b[c++]=224|m>>12}else{if(c+3>=d)break;b[c++]=240|m>>18;b[c++]=128|m>>12&63}b[c++]=128|m>>6&63}b[c++]=128|m&63}}b[c]=0;return c-e}
function na(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var y,C,oa,D,E,pa;function qa(){var a=ia.buffer;h.HEAP8=y=new Int8Array(a);h.HEAP16=oa=new Int16Array(a);h.HEAP32=D=new Int32Array(a);h.HEAPU8=C=new Uint8Array(a);h.HEAPU16=new Uint16Array(a);h.HEAPU32=E=new Uint32Array(a);h.HEAPF32=new Float32Array(a);h.HEAPF64=pa=new Float64Array(a)}var ra,sa=[],ta=[],ua=[];function va(){var a=h.preRun.shift();sa.unshift(a)}
var F=0,wa=null,G=null;function q(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";l(a);ja=!0;ka=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}function xa(a){return a.startsWith("data:application/octet-stream;base64,")}var H;H="example.wasm";if(!xa(H)){var ya=H;H=h.locateFile?h.locateFile(ya,k):k+ya}function za(a){try{if(a==H&&p)return new Uint8Array(p);if(fa)return fa(a);throw"both async and sync fetching of the wasm failed";}catch(b){q(b)}}
function Aa(a){return p||"function"!=typeof fetch?Promise.resolve().then(function(){return za(a)}):fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return za(a)})}function Ba(a,b,c){return Aa(a).then(function(d){return WebAssembly.instantiate(d,b)}).then(function(d){return d}).then(c,function(d){l("failed to asynchronously prepare wasm: "+d);q(d)})}
function Ca(a,b){var c=H;return p||"function"!=typeof WebAssembly.instantiateStreaming||xa(c)||"function"!=typeof fetch?Ba(c,a,b):fetch(c,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,a).then(b,function(e){l("wasm streaming compile failed: "+e);l("falling back to ArrayBuffer instantiation");return Ba(c,a,b)})})}var I,J,Da={332624:()=>"undefined"!==typeof wasmOffsetConverter};
function Ea(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Fa(a){for(;0<a.length;)a.shift()(h)}
var Ga=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},L=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ga(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ha=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Ia=a=>{if("/"===
a)return"/";a=L(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function Ja(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}return()=>q("randomDevice")}
function Ka(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ga(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function La(a,b){var c=Array(na(a)+1);a=ma(a,c,0,c.length);b&&(c.length=a);return c}var Ma=[];function Na(a,b){Ma[a]={input:[],V:[],fa:b};Oa(a,Pa)}
var Pa={open:function(a){var b=Ma[a.node.ha];if(!b)throw new M(43);a.U=b;a.seekable=!1},close:function(a){a.U.fa.ka(a.U)},ka:function(a){a.U.fa.ka(a.U)},read:function(a,b,c,d){if(!a.U||!a.U.fa.Ba)throw new M(60);for(var e=0,g=0;g<d;g++){try{var m=a.U.fa.Ba(a.U)}catch(t){throw new M(29);}if(void 0===m&&0===e)throw new M(6);if(null===m||void 0===m)break;e++;b[c+g]=m}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.U||!a.U.fa.ua)throw new M(60);try{for(var e=0;e<d;e++)a.U.fa.ua(a.U,
b[c+e])}catch(g){throw new M(29);}d&&(a.node.timestamp=Date.now());return e}},Qa={Ba:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=La(b,!0)}return a.input.shift()},ua:function(a,b){null===b||10===b?(ha(w(a.V,0)),a.V=[]):0!=b&&a.V.push(b)},ka:function(a){a.V&&0<a.V.length&&(ha(w(a.V,0)),a.V=[])}},Ra={ua:function(a,
b){null===b||10===b?(l(w(a.V,0)),a.V=[]):0!=b&&a.V.push(b)},ka:function(a){a.V&&0<a.V.length&&(l(w(a.V,0)),a.V=[])}},N={X:null,aa:function(){return N.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new M(63);N.X||(N.X={dir:{node:{W:N.P.W,Y:N.P.Y,ga:N.P.ga,la:N.P.la,Ha:N.P.Ha,Ja:N.P.Ja,Ia:N.P.Ia,Ga:N.P.Ga,oa:N.P.oa},stream:{ca:N.R.ca}},file:{node:{W:N.P.W,Y:N.P.Y},stream:{ca:N.R.ca,read:N.R.read,write:N.R.write,xa:N.R.xa,Da:N.R.Da,na:N.R.na}},
link:{node:{W:N.P.W,Y:N.P.Y,ia:N.P.ia},stream:{}},ya:{node:{W:N.P.W,Y:N.P.Y},stream:Sa}});c=Ta(a,b,c,d);16384===(c.mode&61440)?(c.P=N.X.dir.node,c.R=N.X.dir.stream,c.S={}):32768===(c.mode&61440)?(c.P=N.X.file.node,c.R=N.X.file.stream,c.T=0,c.S=null):40960===(c.mode&61440)?(c.P=N.X.link.node,c.R=N.X.link.stream):8192===(c.mode&61440)&&(c.P=N.X.ya.node,c.R=N.X.ya.stream);c.timestamp=Date.now();a&&(a.S[b]=c,a.timestamp=c.timestamp);return c},eb:function(a){return a.S?a.S.subarray?a.S.subarray(0,a.T):
new Uint8Array(a.S):new Uint8Array(0)},za:function(a,b){var c=a.S?a.S.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.S,a.S=new Uint8Array(b),0<a.T&&a.S.set(c.subarray(0,a.T),0))},Wa:function(a,b){if(a.T!=b)if(0==b)a.S=null,a.T=0;else{var c=a.S;a.S=new Uint8Array(b);c&&a.S.set(c.subarray(0,Math.min(b,a.T)));a.T=b}},P:{W:function(a){var b={};b.Oa=8192===(a.mode&61440)?a.id:1;b.ta=a.id;b.mode=a.mode;b.Va=1;b.uid=0;b.Pa=0;b.ha=a.ha;16384===(a.mode&61440)?b.size=
4096:32768===(a.mode&61440)?b.size=a.T:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Ka=new Date(a.timestamp);b.Ta=new Date(a.timestamp);b.Na=new Date(a.timestamp);b.La=4096;b.Ma=Math.ceil(b.size/b.La);return b},Y:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&N.Wa(a,b.size)},ga:function(){throw Ua[44];},la:function(a,b,c,d){return N.createNode(a,b,c,d)},Ha:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Va(b,c)}catch(g){}if(d)for(var e in d.S)throw new M(55);
}delete a.parent.S[a.name];a.parent.timestamp=Date.now();a.name=c;b.S[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Ja:function(a,b){delete a.S[b];a.timestamp=Date.now()},Ia:function(a,b){var c=Va(a,b),d;for(d in c.S)throw new M(55);delete a.S[b];a.timestamp=Date.now()},Ga:function(a){var b=[".",".."],c;for(c in a.S)a.S.hasOwnProperty(c)&&b.push(c);return b},oa:function(a,b,c){a=N.createNode(a,b,41471,0);a.link=c;return a},ia:function(a){if(40960!==(a.mode&61440))throw new M(28);return a.link}},
R:{read:function(a,b,c,d,e){var g=a.node.S;if(e>=a.node.T)return 0;a=Math.min(a.node.T-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===y.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.S||a.S.subarray)){if(g)return a.S=b.subarray(c,c+d),a.T=d;if(0===a.T&&0===e)return a.S=b.slice(c,c+d),a.T=d;if(e+d<=a.T)return a.S.set(b.subarray(c,c+d),e),d}N.za(a,e+d);if(a.S.subarray&&b.subarray)a.S.set(b.subarray(c,
c+d),e);else for(g=0;g<d;g++)a.S[e+g]=b[c+g];a.T=Math.max(a.T,e+d);return d},ca:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.T);if(0>b)throw new M(28);return b},xa:function(a,b,c){N.za(a.node,b+c);a.node.T=Math.max(a.node.T,b+c)},Da:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new M(43);a=a.node.S;if(e&2||a.buffer!==y.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;b=65536*Math.ceil(b/65536);(e=
Wa(65536,b))?(C.fill(0,e,e+b),b=e):b=0;if(!b)throw new M(48);y.set(a,b)}else c=!1,b=a.byteOffset;return{gb:b,cb:c}},na:function(a,b,c,d){N.R.write(a,b,0,d,c,!1);return 0}}},Xa=null,Ya={},O=[],Za=1,Q=null,$a=!0,M=null,Ua={},R=(a,b={})=>{a=Ka(a);if(!a)return{path:"",node:null};b=Object.assign({Aa:!0,va:0},b);if(8<b.va)throw new M(32);a=a.split("/").filter(m=>!!m);for(var c=Xa,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=Va(c,a[e]);d=L(d+"/"+a[e]);c.ma&&(!g||g&&b.Aa)&&(c=c.ma.root);
if(!g||b.ra)for(g=0;40960===(c.mode&61440);)if(c=ab(d),d=Ka(Ha(d),c),c=R(d,{va:b.va+1}).node,40<g++)throw new M(32);}return{path:d,node:c}},bb=a=>{for(var b;;){if(a===a.parent)return a=a.aa.Ea,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},cb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Q.length},Va=(a,b)=>{var c;if(c=(c=db(a,"x"))?c:a.P.ga?0:2)throw new M(c,a);for(c=Q[cb(a.id,b)];c;c=c.Ua){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.P.ga(a,
b)},Ta=(a,b,c,d)=>{a=new eb(a,b,c,d);b=cb(a.parent.id,a.name);a.Ua=Q[b];return Q[b]=a},fb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},gb=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},db=(a,b)=>{if($a)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},hb=(a,b)=>{try{return Va(a,b),20}catch(c){}return db(a,"wx")},ib=(a=0)=>{for(;4096>=a;a++)if(!O[a])return a;throw new M(33);},jb=(a,b)=>{S||(S=function(){this.ja=
{}},S.prototype={},Object.defineProperties(S.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.ja.flags},set:function(c){this.ja.flags=c}},position:{get:function(){return this.ja.position},set:function(c){this.ja.position=c}}}));a=Object.assign(new S,a);b=ib(b);a.ba=b;return O[b]=a},Sa={open:a=>{a.R=Ya[a.node.ha].R;a.R.open&&a.R.open(a)},ca:()=>{throw new M(70);}},Oa=(a,b)=>{Ya[a]={R:b}},kb=(a,b)=>{var c="/"===b,d=!b;if(c&&Xa)throw new M(10);
if(!c&&!d){var e=R(b,{Aa:!1});b=e.path;e=e.node;if(e.ma)throw new M(10);if(16384!==(e.mode&61440))throw new M(54);}b={type:a,fb:{},Ea:b,Sa:[]};a=a.aa(b);a.aa=b;b.root=a;c?Xa=a:e&&(e.ma=b,e.aa&&e.aa.Sa.push(b))},T=(a,b,c)=>{var d=R(a,{parent:!0}).node;a=Ia(a);if(!a||"."===a||".."===a)throw new M(28);var e=hb(d,a);if(e)throw new M(e);if(!d.P.la)throw new M(63);return d.P.la(d,a,b,c)},lb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);T(a,b|8192,c)},mb=(a,b)=>{if(!Ka(a))throw new M(44);var c=R(b,{parent:!0}).node;
if(!c)throw new M(44);b=Ia(b);var d=hb(c,b);if(d)throw new M(d);if(!c.P.oa)throw new M(63);c.P.oa(c,b,a)},ab=a=>{a=R(a).node;if(!a)throw new M(44);if(!a.P.ia)throw new M(28);return Ka(bb(a.parent),a.P.ia(a))},ob=(a,b,c)=>{if(""===a)throw new M(44);if("string"==typeof b){var d=fb[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=L(a);try{e=R(a,{ra:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&
128)throw new M(20);}else e=T(a,c,0),d=!0;if(!e)throw new M(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new M(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==gb(b)||b&512)?31:db(e,gb(b)):44))throw new M(c);if(b&512&&!d){c=e;c="string"==typeof c?R(c,{ra:!0}).node:c;if(!c.P.Y)throw new M(63);if(16384===(c.mode&61440))throw new M(31);if(32768!==(c.mode&61440))throw new M(28);if(d=db(c,"w"))throw new M(d);c.P.Y(c,{size:0,timestamp:Date.now()})}b&=
-131713;e=jb({node:e,path:bb(e),flags:b,seekable:!0,position:0,R:e.R,bb:[],error:!1});e.R.open&&e.R.open(e);!h.logReadFiles||b&1||(nb||(nb={}),a in nb||(nb[a]=1));return e},pb=(a,b,c)=>{if(null===a.ba)throw new M(8);if(!a.seekable||!a.R.ca)throw new M(70);if(0!=c&&1!=c&&2!=c)throw new M(28);a.position=a.R.ca(a,b,c);a.bb=[]},qb=()=>{M||(M=function(a,b){this.name="ErrnoError";this.node=b;this.Xa=function(c){this.$=c};this.Xa(a);this.message="FS error"},M.prototype=Error(),M.prototype.constructor=M,
[44].forEach(a=>{Ua[a]=new M(a);Ua[a].stack="<generic error, no stack>"}))},rb,sb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},U=(a,b,c)=>{a=L("/dev/"+a);var d=sb(!!b,!!c);tb||(tb=64);var e=tb++<<8|0;Oa(e,{open:g=>{g.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(g,m,t,v)=>{for(var n=0,x=0;x<v;x++){try{var A=b()}catch(B){throw new M(29);}if(void 0===A&&0===n)throw new M(6);if(null===A||void 0===A)break;n++;m[t+x]=A}n&&(g.node.timestamp=Date.now());return n},write:(g,m,t,v)=>
{for(var n=0;n<v;n++)try{c(m[t+n])}catch(x){throw new M(29);}v&&(g.node.timestamp=Date.now());return n}});lb(a,d,e)},tb,V={},S,nb,W=void 0;function X(){W+=4;return D[W-4>>2]}function Y(a){a=O[a];if(!a)throw new M(8);return a}function ub(a){return 0===a%4&&(0!==a%100||0===a%400)}var vb=[0,31,60,91,121,152,182,213,244,274,305,335],wb=[0,31,59,90,120,151,181,212,243,273,304,334];function xb(a){return(ub(a.getFullYear())?vb:wb)[a.getMonth()]+a.getDate()-1}var yb={};
function zb(a){a instanceof Ea||"unwind"==a||ea(1,a)}function Ab(a){ka=a;if(!noExitRuntime){if(h.onExit)h.onExit(a);ja=!0}ea(a,new Ea(a))}function Bb(a){ka=a;Ab(a)}function Cb(a){if(!ja)try{if(a(),!noExitRuntime)try{Bb(ka)}catch(b){zb(b)}}catch(b){zb(b)}}var Db;Db=()=>performance.now();function Eb(a){var b=na(a)+1,c=Fb(b);c&&ma(a,y,c,b);return c}var Gb=[];function Hb(){q("Cannot use convertFrameToPC (needed by __builtin_return_address) without -sUSE_OFFSET_CONVERTER");return 0}var Z={};
function Ib(a){a.forEach(b=>{var c=Hb();c&&(Z[c]=b)})}function Jb(){var a=Error();if(!a.stack){try{throw Error();}catch(b){a=b}if(!a.stack)return"(no stack trace available)"}return a.stack.toString()}var Kb={};
function Lb(){if(!Mb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Kb)void 0===Kb[b]?delete a[b]:a[b]=Kb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Mb=c}return Mb}var Mb;function Nb(a,b){Nb.Fa||(Nb.Fa=Ja());for(var c=0;c<b;c++)y[a+c>>0]=Nb.Fa();return 0}
var Ob=[31,29,31,30,31,30,31,31,30,31,30,31],Pb=[31,28,31,30,31,30,31,31,30,31,30,31];
function Qb(a,b,c,d){function e(f,r,u){for(f="number"==typeof f?f.toString():f||"";f.length<r;)f=u[0]+f;return f}function g(f,r){return e(f,r,"0")}function m(f,r){function u(K){return 0>K?-1:0<K?1:0}var z;0===(z=u(f.getFullYear()-r.getFullYear()))&&0===(z=u(f.getMonth()-r.getMonth()))&&(z=u(f.getDate()-r.getDate()));return z}function t(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function v(f){var r=f.da;for(f=new Date((new Date(f.ea+1900,0,1)).getTime());0<r;){var u=f.getMonth(),z=(ub(f.getFullYear())?Ob:Pb)[u];if(r>z-f.getDate())r-=z-f.getDate()+1,f.setDate(1),11>u?f.setMonth(u+1):(f.setMonth(0),f.setFullYear(f.getFullYear()+1));else{f.setDate(f.getDate()+r);break}}u=new Date(f.getFullYear()+1,0,4);r=t(new Date(f.getFullYear(),
0,4));u=t(u);return 0>=m(r,f)?0>=m(u,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var n=D[d+40>>2];d={$a:D[d>>2],Za:D[d+4>>2],pa:D[d+8>>2],wa:D[d+12>>2],qa:D[d+16>>2],ea:D[d+20>>2],Z:D[d+24>>2],da:D[d+28>>2],ib:D[d+32>>2],Ya:D[d+36>>2],ab:n?n?w(C,n):"":""};c=c?w(C,c):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var x in n)c=c.replace(new RegExp(x,"g"),n[x]);var A="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),B="January February March April May June July August September October November December".split(" ");n={"%a":function(f){return A[f.Z].substring(0,3)},"%A":function(f){return A[f.Z]},"%b":function(f){return B[f.qa].substring(0,
3)},"%B":function(f){return B[f.qa]},"%C":function(f){return g((f.ea+1900)/100|0,2)},"%d":function(f){return g(f.wa,2)},"%e":function(f){return e(f.wa,2," ")},"%g":function(f){return v(f).toString().substring(2)},"%G":function(f){return v(f)},"%H":function(f){return g(f.pa,2)},"%I":function(f){f=f.pa;0==f?f=12:12<f&&(f-=12);return g(f,2)},"%j":function(f){for(var r=0,u=0;u<=f.qa-1;r+=(ub(f.ea+1900)?Ob:Pb)[u++]);return g(f.wa+r,3)},"%m":function(f){return g(f.qa+1,2)},"%M":function(f){return g(f.Za,
2)},"%n":function(){return"\n"},"%p":function(f){return 0<=f.pa&&12>f.pa?"AM":"PM"},"%S":function(f){return g(f.$a,2)},"%t":function(){return"\t"},"%u":function(f){return f.Z||7},"%U":function(f){return g(Math.floor((f.da+7-f.Z)/7),2)},"%V":function(f){var r=Math.floor((f.da+7-(f.Z+6)%7)/7);2>=(f.Z+371-f.da-2)%7&&r++;if(r)53==r&&(u=(f.Z+371-f.da)%7,4==u||3==u&&ub(f.ea)||(r=1));else{r=52;var u=(f.Z+7-f.da-1)%7;(4==u||5==u&&ub(f.ea%400-1))&&r++}return g(r,2)},"%w":function(f){return f.Z},"%W":function(f){return g(Math.floor((f.da+
7-(f.Z+6)%7)/7),2)},"%y":function(f){return(f.ea+1900).toString().substring(2)},"%Y":function(f){return f.ea+1900},"%z":function(f){f=f.Ya;var r=0<=f;f=Math.abs(f)/60;return(r?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":function(f){return f.ab},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(x in n)c.includes(x)&&(c=c.replace(new RegExp(x,"g"),n[x](d)));c=c.replace(/\0\0/g,"%");x=La(c,!1);if(x.length>b)return 0;y.set(x,a);return x.length-1}
function eb(a,b,c,d){a||(a=this);this.parent=a;this.aa=a.aa;this.ma=null;this.id=Za++;this.name=b;this.mode=c;this.P={};this.R={};this.ha=d}Object.defineProperties(eb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});qb();Q=Array(4096);kb(N,"/");T("/tmp",16895,0);T("/home",16895,0);T("/home/web_user",16895,0);
(()=>{T("/dev",16895,0);Oa(259,{read:()=>0,write:(b,c,d,e)=>e});lb("/dev/null",259);Na(1280,Qa);Na(1536,Ra);lb("/dev/tty",1280);lb("/dev/tty1",1536);var a=Ja();U("random",a);U("urandom",a);T("/dev/shm",16895,0);T("/dev/shm/tmp",16895,0)})();(()=>{T("/proc",16895,0);var a=T("/proc/self",16895,0);T("/proc/self/fd",16895,0);kb({aa:()=>{var b=Ta(a,"fd",16895,73);b.P={ga:(c,d)=>{var e=O[+d];if(!e)throw new M(8);c={parent:null,aa:{Ea:"fake"},P:{ia:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var Tb={k:function(){return"undefined"!==typeof wasmOffsetConverter},o:function(a,b){ra.get(a)(b)},h:function(a,b,c){W=c;try{var d=Y(a);switch(b){case 0:var e=X();return 0>e?-28:jb(d,e).ba;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=X(),d.flags|=e,0;case 5:return e=X(),oa[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return D[Rb()>>2]=28,-1;default:return-28}}catch(g){if("undefined"==typeof V||"ErrnoError"!==g.name)throw g;return-g.$}},C:function(a,b,c){W=c;try{var d=
Y(a);switch(b){case 21509:case 21505:return d.U?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.U?0:-59;case 21519:if(!d.U)return-59;var e=X();return D[e>>2]=0;case 21520:return d.U?-28:-59;case 21531:a=e=X();if(!d.R.Qa)throw new M(59);return d.R.Qa(d,b,a);case 21523:return d.U?0:-59;case 21524:return d.U?0:-59;default:return-28}}catch(g){if("undefined"==typeof V||"ErrnoError"!==g.name)throw g;return-g.$}},g:function(a,b,c,d){W=d;try{b=b?w(C,b):"";var e=b;if("/"===
e.charAt(0))b=e;else{var g=-100===a?"/":Y(a).path;if(0==e.length)throw new M(44);b=L(g+"/"+e)}var m=d?X():0;return ob(b,c,m).ba}catch(t){if("undefined"==typeof V||"ErrnoError"!==t.name)throw t;return-t.$}},v:function(a,b){try{a=a?w(C,a):"";a:{try{var c=R(a,{ra:!0}).node;if(!c)throw new M(44);if(!c.P.W)throw new M(63);var d=c.P.W(c)}catch(v){if(v&&v.node&&L(a)!==L(bb(v.node))){var e=-54;break a}throw v;}D[b>>2]=d.Oa;D[b+8>>2]=d.ta;D[b+12>>2]=d.mode;E[b+16>>2]=d.Va;D[b+20>>2]=d.uid;D[b+24>>2]=d.Pa;
D[b+28>>2]=d.ha;J=[d.size>>>0,(I=d.size,1<=+Math.abs(I)?0<I?(Math.min(+Math.floor(I/4294967296),4294967295)|0)>>>0:~~+Math.ceil((I-+(~~I>>>0))/4294967296)>>>0:0)];D[b+40>>2]=J[0];D[b+44>>2]=J[1];D[b+48>>2]=4096;D[b+52>>2]=d.Ma;var g=d.Ka.getTime(),m=d.Ta.getTime(),t=d.Na.getTime();J=[Math.floor(g/1E3)>>>0,(I=Math.floor(g/1E3),1<=+Math.abs(I)?0<I?(Math.min(+Math.floor(I/4294967296),4294967295)|0)>>>0:~~+Math.ceil((I-+(~~I>>>0))/4294967296)>>>0:0)];D[b+56>>2]=J[0];D[b+60>>2]=J[1];E[b+64>>2]=g%1E3*1E3;
J=[Math.floor(m/1E3)>>>0,(I=Math.floor(m/1E3),1<=+Math.abs(I)?0<I?(Math.min(+Math.floor(I/4294967296),4294967295)|0)>>>0:~~+Math.ceil((I-+(~~I>>>0))/4294967296)>>>0:0)];D[b+72>>2]=J[0];D[b+76>>2]=J[1];E[b+80>>2]=m%1E3*1E3;J=[Math.floor(t/1E3)>>>0,(I=Math.floor(t/1E3),1<=+Math.abs(I)?0<I?(Math.min(+Math.floor(I/4294967296),4294967295)|0)>>>0:~~+Math.ceil((I-+(~~I>>>0))/4294967296)>>>0:0)];D[b+88>>2]=J[0];D[b+92>>2]=J[1];E[b+96>>2]=t%1E3*1E3;J=[d.ta>>>0,(I=d.ta,1<=+Math.abs(I)?0<I?(Math.min(+Math.floor(I/
4294967296),4294967295)|0)>>>0:~~+Math.ceil((I-+(~~I>>>0))/4294967296)>>>0:0)];D[b+104>>2]=J[0];D[b+108>>2]=J[1];e=0}return e}catch(v){if("undefined"==typeof V||"ErrnoError"!==v.name)throw v;return-v.$}},D:function(){return!0},x:function(a,b){a=new Date(1E3*(E[a>>2]+4294967296*D[a+4>>2]));D[b>>2]=a.getUTCSeconds();D[b+4>>2]=a.getUTCMinutes();D[b+8>>2]=a.getUTCHours();D[b+12>>2]=a.getUTCDate();D[b+16>>2]=a.getUTCMonth();D[b+20>>2]=a.getUTCFullYear()-1900;D[b+24>>2]=a.getUTCDay();D[b+28>>2]=(a.getTime()-
Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},y:function(a,b){a=new Date(1E3*(E[a>>2]+4294967296*D[a+4>>2]));D[b>>2]=a.getSeconds();D[b+4>>2]=a.getMinutes();D[b+8>>2]=a.getHours();D[b+12>>2]=a.getDate();D[b+16>>2]=a.getMonth();D[b+20>>2]=a.getFullYear()-1900;D[b+24>>2]=a.getDay();D[b+28>>2]=xb(a)|0;D[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();D[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,
c))|0},z:function(a){var b=new Date(D[a+20>>2]+1900,D[a+16>>2],D[a+12>>2],D[a+8>>2],D[a+4>>2],D[a>>2],0),c=D[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),g=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),m=Math.min(g,e);0>c?D[a+32>>2]=Number(e!=g&&m==d):0<c!=(m==d)&&(e=Math.max(g,e),b.setTime(b.getTime()+6E4*((0<c?m:e)-d)));D[a+24>>2]=b.getDay();D[a+28>>2]=xb(b)|0;D[a>>2]=b.getSeconds();D[a+4>>2]=b.getMinutes();D[a+8>>2]=b.getHours();D[a+12>>2]=b.getDate();
D[a+16>>2]=b.getMonth();D[a+20>>2]=b.getYear();return b.getTime()/1E3|0},w:function(a,b,c,d,e,g){try{var m=Y(e);if(c&2){if(32768!==(m.node.mode&61440))throw new M(43);d&2||m.R.na&&m.R.na(m,C.slice(a,a+b),g,b,d)}}catch(t){if("undefined"==typeof V||"ErrnoError"!==t.name)throw t;return-t.$}},q:function(a,b){yb[a]&&(clearTimeout(yb[a].id),delete yb[a]);if(!b)return 0;var c=setTimeout(()=>{delete yb[a];Cb(()=>Sb(a,Db()))},b);yb[a]={id:c,hb:b};return 0},u:function(a,b,c){function d(v){return(v=v.toTimeString().match(/\(([A-Za-z ]+)\)$/))?
v[1]:"GMT"}var e=(new Date).getFullYear(),g=new Date(e,0,1),m=new Date(e,6,1);e=g.getTimezoneOffset();var t=m.getTimezoneOffset();E[a>>2]=60*Math.max(e,t);D[b>>2]=Number(e!=t);a=d(g);b=d(m);a=Eb(a);b=Eb(b);t<e?(E[c>>2]=a,E[c+4>>2]=b):(E[c>>2]=b,E[c+4>>2]=a)},a:function(){q("")},l:function(a,b,c){Gb.length=0;var d;for(c>>=2;d=C[b++];)c+=105!=d&c,Gb.push(105==d?D[c]:pa[c++>>1]),++c;return Da[a].apply(null,Gb)},E:function(){return Date.now()},t:function(){return 2147483648},b:Db,j:function(){q("Cannot use emscripten_pc_get_function without -sUSE_OFFSET_CONVERTER")},
s:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,g=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var m=ia.buffer;try{ia.grow(g.call(e,2147483648,d)-m.byteLength+65535>>>16);qa();var t=1;break a}catch(v){}t=void 0}if(t)return!0}return!1},p:function(){var a=Jb().split("\n");"Error"==a[0]&&a.shift();Ib(a);Z.Ca=Hb();Z.Ra=a;return Z.Ca},m:function(a,b,c){if(Z.Ca==a)var d=Z.Ra;else d=Jb().split("\n"),"Error"==d[0]&&
d.shift(),Ib(d);for(var e=3;d[e]&&Hb()!=a;)++e;for(a=0;a<c&&d[a+e];++a)D[b+4*a>>2]=Hb();return a},A:function(a,b){var c=0;Lb().forEach(function(d,e){var g=b+c;e=E[a+4*e>>2]=g;for(g=0;g<d.length;++g)y[e++>>0]=d.charCodeAt(g);y[e>>0]=0;c+=d.length+1});return 0},B:function(a,b){var c=Lb();E[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0},e:Bb,c:function(a){try{var b=Y(a);if(null===b.ba)throw new M(8);b.sa&&(b.sa=null);try{b.R.close&&b.R.close(b)}catch(c){throw c;}finally{O[b.ba]=
null}b.ba=null;return 0}catch(c){if("undefined"==typeof V||"ErrnoError"!==c.name)throw c;return c.$}},f:function(a,b,c,d){try{a:{var e=Y(a);a=b;for(var g,m=b=0;m<c;m++){var t=E[a>>2],v=E[a+4>>2];a+=8;var n=e,x=t,A=v,B=g,f=y;if(0>A||0>B)throw new M(28);if(null===n.ba)throw new M(8);if(1===(n.flags&2097155))throw new M(8);if(16384===(n.node.mode&61440))throw new M(31);if(!n.R.read)throw new M(28);var r="undefined"!=typeof B;if(!r)B=n.position;else if(!n.seekable)throw new M(70);var u=n.R.read(n,f,x,
A,B);r||(n.position+=u);var z=u;if(0>z){var K=-1;break a}b+=z;if(z<v)break;"undefined"!==typeof g&&(g+=z)}K=b}E[d>>2]=K;return 0}catch(P){if("undefined"==typeof V||"ErrnoError"!==P.name)throw P;return P.$}},n:function(a,b,c,d,e){try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var g=Y(a);pb(g,b,d);J=[g.position>>>0,(I=g.position,1<=+Math.abs(I)?0<I?(Math.min(+Math.floor(I/4294967296),4294967295)|0)>>>0:~~+Math.ceil((I-+(~~I>>>0))/4294967296)>>>0:0)];D[e>>2]=J[0];D[e+
4>>2]=J[1];g.sa&&0===b&&0===d&&(g.sa=null);return 0}catch(m){if("undefined"==typeof V||"ErrnoError"!==m.name)throw m;return m.$}},d:function(a,b,c,d){try{a:{var e=Y(a);a=b;for(var g,m=b=0;m<c;m++){var t=E[a>>2],v=E[a+4>>2];a+=8;var n=e,x=t,A=v,B=g,f=y;if(0>A||0>B)throw new M(28);if(null===n.ba)throw new M(8);if(0===(n.flags&2097155))throw new M(8);if(16384===(n.node.mode&61440))throw new M(31);if(!n.R.write)throw new M(28);n.seekable&&n.flags&1024&&pb(n,0,2);var r="undefined"!=typeof B;if(!r)B=n.position;
else if(!n.seekable)throw new M(70);var u=n.R.write(n,f,x,A,B,void 0);r||(n.position+=u);var z=u;if(0>z){var K=-1;break a}b+=z;"undefined"!==typeof g&&(g+=z)}K=b}E[d>>2]=K;return 0}catch(P){if("undefined"==typeof V||"ErrnoError"!==P.name)throw P;return P.$}},F:Nb,i:Ab,r:function(a,b,c,d){return Qb(a,b,c,d)}};
(function(){function a(c){c=c.exports;h.asm=c;ia=h.asm.G;qa();ra=h.asm.J;ta.unshift(h.asm.H);F--;h.monitorRunDependencies&&h.monitorRunDependencies(F);if(0==F&&(null!==wa&&(clearInterval(wa),wa=null),G)){var d=G;G=null;d()}return c}var b={a:Tb};F++;h.monitorRunDependencies&&h.monitorRunDependencies(F);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){l("Module.instantiateWasm callback failed with error: "+c),ba(c)}Ca(b,function(c){a(c.instance)}).catch(ba);return{}})();
h._solve=function(){return(h._solve=h.asm.I).apply(null,arguments)};function Rb(){return(Rb=h.asm.K).apply(null,arguments)}var Fb=h._malloc=function(){return(Fb=h._malloc=h.asm.L).apply(null,arguments)};h._free=function(){return(h._free=h.asm.M).apply(null,arguments)};function Wa(){return(Wa=h.asm.N).apply(null,arguments)}function Sb(){return(Sb=h.asm.O).apply(null,arguments)}h.___start_em_js=332681;h.___stop_em_js=332742;var Ub;G=function Vb(){Ub||Wb();Ub||(G=Vb)};
function Wb(){function a(){if(!Ub&&(Ub=!0,h.calledRun=!0,!ja)){h.noFSInit||rb||(rb=!0,qb(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?U("stdin",h.stdin):mb("/dev/tty","/dev/stdin"),h.stdout?U("stdout",null,h.stdout):mb("/dev/tty","/dev/stdout"),h.stderr?U("stderr",null,h.stderr):mb("/dev/tty1","/dev/stderr"),ob("/dev/stdin",0),ob("/dev/stdout",1),ob("/dev/stderr",1));$a=!1;Fa(ta);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&
(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();ua.unshift(b)}Fa(ua)}}if(!(0<F)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)va();Fa(sa);0<F||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();Wb();


  return createModule.ready
}

);
})();

self.addEventListener('message', async (event) => {
  if (!self.solver) {
    self.solver = await createSolver();  
  }

  const model = event.data.model;
  const modelPtr = self.solver._malloc(model.length);
  self.solver.HEAPU8.set(model, modelPtr);

  const solution = self.solver._solve(modelPtr, model.length);

  event.source.postMessage({ solution });
})
